### ISSUE TITLE
Bug: TypeError when enabling `use_tabu` in cal2005 experiment

### ISSUE THREAD

**Issue by sjvrijn** [JustinStarreveld/ROBIST#5]
When enabling `use_tabu` in line 126 of `tp_experiments_cal2005_yan2013.py`, the program raises a TypeError for trying to add a list object to a set, since a list is not hashable.

Traceback:

```bash
$ python examples/tp_experiments_cal2005_yan2013.py
k=2

Traceback (most recent call last):
  File "/home/sander/src/ROBIST/examples/tp_experiments_cal2005_yan2013.py", line 133, in <module>
    S_history) = algorithm.run(stop_criteria=stop_criteria,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/src/ROBIST/src/robist/robist.py", line 231, in run
    tabu_remove = self._get_tabu_remove(S_indices, S_history)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/src/ROBIST/src/robist/robist.py", line 415, in _get_tabu_remove
    tabu_remove.add([i for i in S_current if i not in S])
TypeError: unhashable type: 'list'
```

**Comment by sjvrijn** [comment]
closed by 81c8691
